Repository data-describe/data-describe, pull requests merged in 2020-12, with the labels that each got.

#416 Add dependabot
  .github/workflows/dependabot.yml
Labels: maintenance

#417 Fix dependabot config location
  .github/dependabot.yml
Labels: exclude notes

#420 Update conda setup gh action
  .github/workflows/ci-master.yml
  .github/workflows/ci-pr.yml
  .github/workflows/dependabot.yml
  .github/workflows/publish-master-docs.yml
  .github/workflows/publish-release-docs.yml
Labels: exclude notes, maintenance

#414 bump to v0.1.0b3
  data_describe/_version.py
Labels: exclude notes

#423 Added workflow dispatch events
  .github/workflows/ci-master.yml
  .github/workflows/publish-master-docs.yml
  .github/workflows/release-notes.yml
Labels: maintenance

#424 Add manual trigger to release doc publish workflow
  .github/workflows/publish-release-docs.yml
Labels: exclude notes, maintenance

#425 Update conda setup action for release doc workflow
  .github/workflows/publish-release-docs.yml
Labels: exclude notes, maintenance

#426 Fixed the midpoint for plotly correlation color bar to 0 and removed descartes from requirements.txt
  data_describe/core/correlation.py
  examples/Correlation_Matrix.ipynb
  requirements.txt
Labels: bug

#428 Fixed zero counts calculation in data_summary and added to unit test
  data_describe/core/summary.py
  examples/Data_Summary.ipynb
  tests/conftest.py
  tests/test_summary.py
Labels: bug
