Repository data-describe/data-describe, pull requests merged in 2020-11, with the labels that each got.

#372 Added redirect page
  docs/index.html
  index.html
Labels: enhancement

#380 Remove untitled notebook
  examples/Untitled.ipynb
Labels: bug, exclude notes

#386 Added kwargs to text preprocessing functions: filter_dictionary, create_doc_term_matrix, and create_tfidf_matrix
  data_describe/text/text_preprocessing.py
Labels: bug

#387 Fix broken sphinx doc build
  docs/source/_notebooks/tutorial.ipynb
  docs/source/conf.py
Labels: exclude notes, maintenance

#388 Switch to deploy key instead of github token
  .github/workflows/publish-master-docs.yml
  .github/workflows/publish-release-docs.yml
Labels: exclude notes, maintenance

#377 Updated contributing guide
  CONTRIBUTING.md
  docs/source/_notebooks/contributing_guide.ipynb
  docs/source/_notebooks/developer_guide.ipynb
  docs/source/_notebooks/imgs/assignee.PNG
  docs/source/_notebooks/imgs/bug-report-page.PNG
  docs/source/_notebooks/imgs/edit-readme.PNG
  docs/source/_notebooks/imgs/fork.PNG
  docs/source/_notebooks/imgs/open-pull-request.PNG
  docs/source/index.rst
Labels: documentation

#383 Reworked data summary
  data_describe/core/summary.py
  examples/Data_Summary.ipynb
  examples/Quick_Start.ipynb
  tests/test_summary.py
Labels: enhancement

#394 Removed Extra Cell in User Guide
  docs/source/_notebooks/user_guide.ipynb
Labels: bug

#399 Disabled checks on draft PRs
  .github/workflows/ci-master.yml
  .github/workflows/ci-pr.yml
Labels: ci, enhancement, maintenance

#403 Fixed data summary data size formatter
  data_describe/core/summary.py
  examples/Data_Summary.ipynb
  examples/Quick_Start.ipynb
Labels: bug, exclude notes

#393 Added progress bar when fitting topic model
  data_describe/text/topic_modeling.py
  etc/doc-environment.yml
  etc/test-environment.yml
  examples/Topic_Modeling.ipynb
  requirements.txt
  setup.py
Labels: enhancement

#396 Fixed backend recursion bug
  data_describe/backends/_backends.py
  tests/test_backend.py
Labels: bug

#398 Fixed image links from #377
  docs/source/_notebooks/contributing_guide.ipynb
Labels: bug, exclude notes
