Repository data-describe/data-describe, pull requests merged in 2020-10, with the labels that each got.

#350 Added code coverage
  .github/workflows/ci.yml
Labels: maintenance

#343 Added legend and moved to object-oriented mpl API
  data_describe/core/heatmap.py
  tests/test_data_heatmap.py
Labels: bug

#354 Changed codecov to informational
  codecov.yml
Labels: maintenance

#346 Resolved missing imports
  data_describe/_widget.py
  data_describe/backends/_backends.py
  data_describe/compat/__init__.py
  data_describe/compat/_dependency.py
  data_describe/compat/_notebook.py
  data_describe/core/clustering.py
  data_describe/core/correlation.py
  data_describe/core/heatmap.py
  data_describe/core/time.py
  data_describe/text/topic_modeling.py
  setup.py
  tests/test_widget.py
Labels: bug

#355 Updated CI environment
  .github/workflows/ci.yml
  etc/test-environment.yml
Labels: maintenance

#348 Updated setup() metadata for PyPI
  setup.py
Labels: bug

#347 Fixed backend logic for none
  .github/workflows/ci.yml
  data_describe/backends/_backends.py
  etc/test-environment.yml
Labels: bug

#357 Bump to 0.1.0b2
  data_describe/_version.py
Labels: exclude notes

#361 Custom domain
  CONTRIBUTING.md
  README.md
  setup.py
Labels: exclude notes

#364 Added badges to README
  README.md
Labels: exclude notes

#368 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#369 Added support for Python 3.6
  .github/workflows/release.yml
  setup.py
Labels: enhancement
